spring.application.name=innovatechv1-backend-ventas


spring.datasource.url=jdbc:mysql://${DB_IP_PRIVADA}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


spring.jpa.database=mysql
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

springdoc.swagger-ui.path=/swagger-ui.html

server.port=8082